---
all:
  vars:
    ansible_user: "{{ lookup('env', 'NETWORK_USER') | default('admin', true) }}"
    ansible_password: "{{ lookup('env', 'NETWORK_PASSWORD') }}"
    ansible_become: yes
    ansible_become_method: enable
  children:
    cisco_ios:
      hosts:
        core-router-01:
          ansible_host: 192.168.1.1
        core-router-02:
          ansible_host: 192.168.1.2
        dist-switch-01:
          ansible_host: 192.168.1.10
      vars:
        ansible_network_os: cisco.ios.ios
        ansible_connection: ansible.netcommon.network_cli
    cisco_nxos:
      hosts:
        nexus-01:
          ansible_host: 192.168.2.1
      vars:
        ansible_network_os: cisco.nxos.nxos
        ansible_connection: ansible.netcommon.network_cli
    juniper_junos:
      hosts:
        srx-fw-01:
          ansible_host: 192.168.3.1
      vars:
        ansible_network_os: junipernetworks.junos.junos
        ansible_connection: ansible.netcommon.netconf
